Repository dvsa/cvs-svc-test-results, pull requests merged in 2023-03, with the labels that each got.

#325 fix(cb2-7633): query test types with multiple vehiclesSubclasses (#323)
  src/handlers/VehicleTestController.ts
Labels: bug, enhancement

#330 feat(cb2-6876) - modify expiry date calculations
  src/handlers/VehicleTestController.ts
  src/models/ITestResultPayload.ts
  src/models/validators/TestResultsSchemaCarSubmitted.ts
  src/models/validators/TestResultsSchemaLGVSubmitted.ts
  src/models/validators/TestResultsSchemaMotorcycleSubmitted.ts
  tests/unit/generateExpiryDate.unitTest.ts
Labels: enhancement

#333 feat(cb2-7727): remove the small trailer type
  src/assets/Enums.ts
  src/utils/validationUtil.ts
Labels: bug

#338 feature(cb2-7652): allow getting cancelled tests
  src/assets/Enums.ts
  src/models/validators/test-types/testTypesSchemaDeskBasedTestsPut.ts
  src/utils/mappingUtil.ts
  tests/unit/getTestResultsBySystemNumberFunction.unitTest.ts
Labels: enhancement
